### ISSUE TITLE
target-csv not working with tap-marketo

### ISSUE THREAD

**Issue by nicholassewitz** [singer-io/tap-marketo#5]
When I try and send marketo data to the singer target-csv I am getting this error 

```
artsy-nicholass:marketo-fulcrum nicholassewitz$ tap-marketo -c config.json -s state.json | target-csv -c csv-config.json
Traceback (most recent call last):
  File "/usr/local/bin/tap-marketo", line 7, in <module>
    from tap_marketo import main
  File "/usr/local/lib/python3.6/site-packages/tap_marketo/__init__.py", line 12, in <module>
    from singer import utils
ImportError: cannot import name 'utils'
```

**Comment by nicholassewitz** [comment]
got it working when i ran on separate virtualenvs now getting this error
```
    sys.exit(main())
  File "/Users/nicholassewitz/marketo-fulcrum/tap-marketo/lib/python3.6/site-packages/tap_marketo/__init__.py", line 320, in main
    do_sync()
  File "/Users/nicholassewitz/marketo-fulcrum/tap-marketo/lib/python3.6/site-packages/tap_marketo/__init__.py", line 267, in do_sync
    singer.write_schema("leads", schema, ["id"])
  File "/Users/nicholassewitz/marketo-fulcrum/tap-marketo/lib/python3.6/site-packages/singer/__init__.py", line 91, in write_schema
    key_properties=key_properties))
  File "/Users/nicholassewitz/marketo-fulcrum/tap-marketo/lib/python3.6/site-packages/singer/__init__.py", line 52, in _write_message
    sys.stdout.write(message.tojson() + '\n')
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by cmerrick** [comment]
Is there more to that stack trace?  Or some stderror output?  BrokenPipe is typically just one python process complaining that the other one died.
